name = "cornucopias/mint_contract"
version = "0.5.0"
license = "GPL-3.0-or-later"
description = "CIP68 Minting And Metadatum Storage Contracts for Cornucopias"

[repository]
user = "cornucopias"
project = "mint_contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.4.9"
source = "github"