name = "aiken-lang/mint_contract"
version = "0.0.2"
license = "GPL-3.0"
description = "CIP68 Minting And Metadatum Storage Contracts for Cornucopias"

[repository]
user = "aiken-lang"
project = "mint_contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.0.0"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "v0.1.5"
source = "github"