name = "aiken-lang/mint_contract"
version = "0.1.0"
license = "GPL-3.0"
description = "CIP68 Minting And Metadatum Storage Contracts for Cornucopias"

[repository]
user = "aiken-lang"
project = "mint_contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "logicalmechanism/assist"
version = "main"
source = "github"